### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by jb510** [shawnhooper/delete-orphaned-multisite-tables#4]
This isn't really an issue.  Just a huge THANK YOU.  I think that's well deserved when 6 year old code "just works"

I just ran this 2021/11/20 on a Multi-site where we spin up temporary sites and then delete them.  I've run the site for years but just noticed the DB was 2GB. It should have been 2MB (seriously).   So I looked and a plugin had gone haywire creating dozens of redundant tables that weren't getting removed...  well more than dozens.  

THANK YOU.
![2021-11-20 at 1 30 PM](https://user-images.githubusercontent.com/801241/142743839-8d2497f2-371b-46f4-bce6-3abb432aabdd.png)

**Comment by shawnhooper** [comment]
@jb510 Thanks for the feedback!  Glad you find the plugin useful.  Wrote this as a quick fix for a friend in the community years ago.  Always happy to see new users discover it.
